import Head from "next/head";
import { Editor } from "@tinymce/tinymce-react";
import { useRef, useState } from "react";

export default function Home() {
  const editorRef = useRef<any>(null);
  const [value, setValue] = useState<string>("");
  const log = () => {
    if (editorRef.current) {
      console.log(editorRef.current.getContent());
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Editor
        tinymceScriptSrc={"/tinymce/tinymce.min.js"}
        onInit={(evt, editor) => (editorRef.current = editor)}
        value={value}
        onEditorChange={(e) => {
          console.log(e);
          setValue(e);
        }}
        init={{
          height: 500,
          menubar: false,
          plugins: [
            "advlist",
            "autolink",
            "lists",
            "link",
            "image",
            "charmap",
            "anchor",
            "searchreplace",
            "visualblocks",
            "code",
            "fullscreen",
            "insertdatetime",
            "media",
            "table",
            "preview",
            "help",
            "wordcount",
          ],
          toolbar:
            "undo redo | blocks | " +
            "bold italic forecolor | alignleft aligncenter " +
            "alignright alignjustify | bullist numlist outdent indent | " +
            "removeformat | image code fullscreen | help",
          content_style:
            "body { font-family:Helvetica,Arial,sans-serif; font-size:14px }",
          image_caption: true,
        }}
      />
      <button onClick={log}>Log editor content</button>
    </>
  );
}
